### PR TITLE
fixes for new bootstrap process

### PR DESCRIPTION
**Pull request by nordicdyno**

### CODE REVIEW

**Comment by afiskon** [comment]
I get:
```
Step 12/15 : COPY config-templates/bootstrap.yaml ./scripts/insolard/bootstrap.yaml
 ---> 4334ecb7b4f1
Step 13/15 : RUN ./bin/insolar bootstrap --config scripts/insolard/bootstrap.yaml   --certificates-out-dir scripts/insolard/discoverynodes/certs
 ---> Running in 69e7d9c98f98
unknown command "bootstrap" for "insolar"
Error: unknown command "bootstrap" for "insolar"
Run 'insolar --help' for usage.
```
on `master` branch. Which branch should I test on?

**Comment by nordicdyno** [comment]
`genesis-contracts-load-on-heavy` branch

**Comment by nordicdyno** [comment]
`INS-2374-refactor-builtins-compile`

**Comment by afiskon** [comment]
Looks good to me. I tested the branch locally and it seem to work properly. Feel free to merge this PR after merging `INS-2374-refactor-builtins-compile`.

**Comment by afiskon** [comment]
9709f97edf38d2bd496c1530c6c27e1b3831c21c 👌

**Pull request merged**
